### ISSUE TITLE
UserWarning: Unknown distribution option: 'long_description_content_type'

### ISSUE THREAD

**Issue by jgiombi** [weblyzard/inscriptis#14]
When executing the setup.py script, I get the following error.

Warning (from warnings module):
  File "C:\Python36\lib\distutils\dist.py", line 261
    warnings.warn(msg)
UserWarning: Unknown distribution option: 'long_description_content_type'

**Comment by AlbertWeichselbraun** [comment]
This warning should go away, if you upgrade setuptools to the most recent version `python3 -m pip install --upgrade setuptools`.

Alternatively you can use `pip3 install .` instead of `python3 setup.py install`.
