### ISSUE TITLE
Failure while parsing Site

### ISSUE THREAD

**Issue by sandrohoerler** [weblyzard/inscriptis#16]
https://www.hbi.ch/de/firmenprofil/mitarbeiter/buero-heidenheim/ 

Büro -> Bro

**Comment by AlbertWeichselbraun** [comment]
hi @sandrohoerler - this fixes the inscript.py client which is relevant to most inscriptis users.

in your case i think that ds9 might have reported an incorrect encoding or that the ds9 encoding is not used. 
(can you check, whether ds9 used an iso-8859-1 encoding for this site).

**Comment by sandrohoerler** [comment]
Hi albert, fixed in inscriptisWSBaseBolt

Am Di., 11. Dez. 2018 um 20:48 Uhr schrieb Albert Weichselbraun <
notifications@github.com>:
