### ISSUE TITLE
Add support for converting HTML into indented text

### ISSUE THREAD

**Issue by electronicous** [weblyzard/inscriptis#18]
For now it only respects newlines when converting to text, could this feature by any chance be implemented?

**Comment by AlbertWeichselbraun** [comment]
I will take a look. Just to be sure that we are both on the same page - could you please provide me with an example of 

 1. the current output (i.e. an example site (url) + the exact way you called inscriptis) and
 2. the output you would like to get.

many thanks, albert :)

**Comment by electronicous** [comment]
Thanks for your reply.

This is what i'm using, you can find the html string [here](https://paste.website/p/38177bdc-9769-40f9-8059-386d399b1df3.txt):
```
from inscriptis import get_text

html = # Multiline HTML string
text = get_text(html)

print(text)
```
This is how it looks like in the terminal currently.
![image](https://user-images.githubusercontent.com/45419292/65392696-c8218f00-dd77-11e9-80c7-8c125c9bc193.png)

I'd like the children to be indented. Something like it is on the site.
![image](https://user-images.githubusercontent.com/45419292/65392708-ebe4d500-dd77-11e9-861c-acb63bfb6354.png)

**Comment by AlbertWeichselbraun** [comment]
I have added an `indentation` option to the library as well as to the command line client.

For instance `inscript.py --indentation extended https://www.dwds.de/wb/ber%C3%BCcksichtigen` renders the web page above as follows

```
...
              berücksichtigen


                Grammatik Verb
                Aussprache Fehler
                Worttrennung be-rück-sich-ti-gen
                Wortbildung mit ›berücksichtigen‹ als Letztglied: ↗ mitberücksichtigen · formal verwandt mit: ↗ unberücksichtigt
                eWDG, 1967

              Bedeutungen

                  1.
                    auf etw., jmdn. Rücksicht nehmen, etw., jmdn. in Betracht ziehen
                      Beispiele:
                      einen besonderen Umstand, die Verhältnisse berücksichtigen
                      das Finanzamt hat seine schwierige Lage weitgehend berücksichtigt
                      Gehaltsempfänger mit niedrigem Einkommen müssen bei Steuererlass besonders berücksichtigt werden
                      daß morgen ... die Zeit abläuft, wo ein Gnadengesuch noch berücksichtigt werden kann [ A. Zweig Grischa 384 ]
                  2.
                    etw., jmdn. beachten, respektieren
                      Beispiele:
                      jmds. Verdienste gebührend berücksichtigen
                      man sollte diesen tüchtigen Menschen unbedingt berücksichtigen
                      wenn der Heingeiger als Vater den letzten Willen seiner so tragisch ums Leben gekommenen Tochter nicht berücksichtige [ O. M. Graf Unruhe 274 ]
...
```

you can also use this when using inscriptis as an library by calling

```python
text = get_text(html, indentation=extended)
```

would this fit your needs?

**Comment by AlbertWeichselbraun** [comment]
The latest inscriptis release (0.0.4.1) should fix this issue.
