### ISSUE TITLE
Mixed text in extraction of table with span

### ISSUE THREAD

**Issue by sudoale** [weblyzard/inscriptis#33]
It seems that inscriptis does something strange in the text extraction of following document:

GoldDocument: https://gitlab.semanticlab.net/careercoach/page-segmentation/-/blob/master/corpus/goldDocuments/www.computer-studio.ch_i283260313085922574995599451274802310613.json
URL: https://www.computer-studio.ch/schulung/ecdl-zertifikat/ecdlbase/

Keyword "Voraussetzung" and the coressponding text content are part of table cells. However the extracted text is a mix of both:

Current:
"`Modul \u00abPC-Einf\u00fchrung mit Windows\u00bb oder gleichwertige Kenntnisse \n`**Voraussetzung** `(Auf Teilnehmende, welche die erforderlichen Vorkenntnisse nicht besitzen, kann keine R\u00fccksicht genommen werden!)\n`"

Gold:
"**Voraussetzung** `Modul \u00abPC-Einf\u00fchrung mit Windows\u00bb oder gleichwertige Kenntnisse (Auf Teilnehmende, welche die erforderlichen Vorkenntnisse nicht besitzen, kann keine R\u00fccksicht genommen werden!)\n`"

**Comment by AlbertWeichselbraun** [comment]
This issue has been resolved in #34 and is available in inscriptis 1.2+.
