### ISSUE TITLE
tag preprocessor example in readme results in an error

### ISSUE THREAD

**Issue by rlskoeser** [weblyzard/inscriptis#39]
the readme includes this example usage under the annotation preprocessors section:
```
$ inscript.py https://www.fhgr.ch \
        -r ./examples/annotation-profile.json \
        -p tag
```

When I try running it, I get this error:
```
ModuleNotFoundError: No module named 'inscriptis.annotation.output.tag'
```

It's not clear from the example whether it's meant to be a placeholder command or a real one (I think the first?); maybe just revise it to use an actual supported preprocessor to avoid confusion

**Comment by AlbertWeichselbraun** [comment]
Thanks for spotting this - I forgot to update the preprocessor name (`tag` has been the old name for the `surface` preprocessor).
