### ISSUE TITLE
web service instructions don't work as written

### ISSUE THREAD

**Issue by rlskoeser** [weblyzard/inscriptis#40]
As far as I can tell the web service only works if you check out the git repository, not from a pip install.  You might think about including it in the python package, but I don't know how important that is.

I think it would be sufficient to amend the instructions to add directions to check out the repository, and then correct the path to `web-service.py` which is now under the `scripts` directory.

**Comment by AlbertWeichselbraun** [comment]
Thank you for pointing this out. I have moved the web service into the Inscriptis package and adjusted the documentation accordingly.
