### ISSUE TITLE
Empty row bug

### ISSUE THREAD

**Issue by Lucas-Gerrand** [weblyzard/inscriptis#6]
Index out of bounds Error

* https://github.com/weblyzard/inscriptis/blob/master/src/inscriptis/html_properties.py#L30
* self.rows[-1].columns[-1] += text

* Possible fix simply :
```
            if not self.rows:
                self.add_row()
            if not self.rows[-1].columns:
                self.add_column()    
```

Sample from [dragnet sample] (https://github.com/seomoz/dragnet_data)

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
    <HTML>
     <HEAD>
      <TITLE>Drop cap initial letter</TITLE>
      <STYLE type="text/css">
       P              { font-size: 12pt; line-height: 1.2 }
       P:first-letter { font-size: 200%; font-style: italic;
                        font-weight: bold; float: left }
       SPAN           { text-transform: uppercase }
      </STYLE>
     </HEAD>
     <BODY>
     <h1>Some more significant words here</h1>
      <P><SPAN><b>The first<b></SPAN> few words of an article
        in The Economist.</p>
        <p>&nbsp;</p>
    
        
     </BODY>
     
    </HTML>
```

Cheers, 
Lucas

**Comment by Lucas-Gerrand** [comment]
Also related: 

Source:
    * http://www.news.com.au/finance/work/melbourne-cup-day-check-yourself-before-you-wreck-yourself/story-e6frfm9r-1226511327171?from=public_rss

Problem:

https://github.com/weblyzard/inscriptis/blob/master/src/inscriptis/html_engine.py#L240

```
    def start_tr(self, attrs):
        
        self.current_table[-1].add_row()
```
Suggested change:

```
    def start_tr(self, attrs):
        if not self.current_table:
            self.current_table.append(Table())
        self.current_table[-1].add_row()
```

Cheers, 
Lucas

**Comment by AlbertWeichselbraun** [comment]
This would be the straight forward fix. I implemented a slightly more complicated approach so that inscriptis now handles tables similar to Chrome and Firefox.
