### ISSUE TITLE
Text mapping to original HTML elements

### ISSUE THREAD

**Issue by ThomasArtin** [weblyzard/inscriptis#77]
Is there a way to map the text to where they were extracted from the HTML? using the XPATH for example?

**Comment by AlbertWeichselbraun** [comment]
not at the moment, since this task is not trivial.

```html
<ul>
  <li>This is an <b>important</b> and <i>urgent</i> message for you.</li>
  <li>The <strong>second</strong> message.
</ul>
``` 
the example above, for instance, would map to different xpaths that all contain parts of the message.

do you have suggestions of how the output of such a mapping should look like?

**Comment by AlbertWeichselbraun** [comment]
I will reopen and address this bug, once someone comes up with a viable suggestion on how such a mapping should look like.
